name: Build Debug APK

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build-debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Make gradlew executable
        run: chmod +x V2rayNG/gradlew

      - name: Build Debug APK
        working-directory: V2rayNG
        run: ./gradlew assembleFdroidDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MrVPN7-debug-apk
          path: V2rayNG/app/build/outputs/apk/**/*.apk